# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  zramSwap.enable = true;

  boot = {
    loader.grub.device = "/dev/sda";
    tmp.cleanOnBoot = true;

    initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "xen_blkfront" "vmw_pvscsi" ];
    initrd.kernelModules = [ "nvme" ];

    kernelModules = [ ];
    extraModulePackages = [ ];
  };

  fileSystems."/" = { device = "/dev/sda1"; fsType = "ext4"; };

  swapDevices = [ ];
}
