name: playground
root: ~/git/evil-playground

windows:
  - playground:
      layout: dfa4,365x91,0,0{283x91,0,0,104,81x91,284,0[81x45,284,0,105,81x45,284,46,107]}
      panes:
        - nvim index.js
        - npm start
        -
