#!/bin/sh

xrdb $HOME/.Xresources
#xsetroot -solid grey
#xterm -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
export XKL_XMODMAP_DISABLE=1
#exec awesome
#exec qtile
#exec razor-session
exec gnome-session
#exec mate-session
#exec gnome-session-cinnamon
