-- local lint = require("lint")
--
-- vim.env.ESLINT_D_PPID = vim.fn.getpid()
--
-- lint.linters_by_ft = {
--   javascript = { "eslint_d" },
--   javascriptreact = { "eslint_d" },
--   typescript = { "eslint_d" },
--   typescriptreact = { "eslint_d" },
-- }
--
-- vim.api.nvim_create_autocmd({ "BufWritePost", "BufReadPost", "InsertLeave", "TextChanged" }, {
--   callback = function()
--     lint.try_lint()
--   end,
-- })
