# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.initrd.supportedFilesystems = ["zfs"]; # boot from zfs
  boot.supportedFilesystems = [ "zfs" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/07dc9224-6a05-4236-9b57-04ff86f79700";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/38B8-F12A";
      fsType = "vfat";
    };

  fileSystems."/mnt/media" =
    { device = "media-pool";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5344569e-af25-47b4-8479-511d0a93a04c"; }
    ];
}
