name: "check"

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
    - name: Build neovim
      run: nix build './modules/neovim#'
    - name: Check neovim
      run: nix flake check './modules/neovim#'
    - name: Check main
      run: nix flake check
