name: "check"

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
#       with:
#         extra_nix_config: |
#           access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: nix build
    - name: Check neovim
      run: nix flake check './modules/neovim#'
    - name: Check main
      run: nix flake check
